### ISSUE TITLE
Incoming mail from Outlook

### ISSUE THREAD

**Issue by PatrickHonorez** [kanboard/plugin-mailgun#4] opened 2016-01-25 08:34 UTC
For task creation from email, everything works fine when email is sent from Gmail (or "Google for work").
However, when sending a mail from Outlook (via Exchange), then the new task description includes what is probably the message header, something like this:  

`<!-- / Font Definitions / @font-face {font-family:Calibri; panose-1:2 15 5 2 2 2 4 3 2 4;} / Style Definitions / p.MsoNormal, li.MsoNormal, div.MsoNormal {margin:0cm; margin-bottom:.0001pt; font-size:11.0pt; font-family:"Calibri","sans-serif";} a:link, span.MsoHyperlink {mso-style-priority:99; color:blue; text-decoration:underline;} a:visited, span.MsoHyperlinkFollowed {mso-style-priority:99; color:purple; text-decoration:underline;} span.EmailStyle17 {mso-style-type:personal-compose; font-family:"Calibri","sans-serif"; color:windowtext;} .MsoChpDefault {mso-style-type:export-only; font-family:"Calibri","sans-serif";} @page WordSection1 {size:612.0pt 792.0pt; margin:72.0pt 72.0pt 72.0pt 72.0pt;} div.WordSection1 {page:WordSection1;} -->`Then comes the message

**Comment by fguillot** [comment] 2016-01-28 18:48
Ok, I will investigate.

**Comment by bdrayer** [comment] 2016-02-01 14:48
I have the same problem. I posted it on https://github.com/fguillot/kanboard/issues/1750 and get an answer with a piece of code from @jtourt. You can perhaps use it.

Best regards

**Comment by fguillot** [comment] 2016-02-09 02:38
I just tried with a Outlook for Mac which is connected to the Exchange server of Office 365 and seems to works for me.

Which version of Outlook are you using? What kind of message did you send? (simple message or complex html).

Note: This plugin works only with simple HTML or plain text messages.

**Comment by bdrayer** [comment] 2016-02-09 07:32
On my case I use HTML (don't know if it's simple or complex HTML) but I get the same problem using Outlook 2010 or eM Client. 

I think that if you remove all HTML headers it will do the job because it's clearly the CSS code that I see in the 2 case.

**Comment by PatDeLux** [comment] 2016-02-09 08:15
Same for me: Html format - did not see a simple or complex option on
Outlook. the message was just a simple "Hi" with some formatting in teh
signature.
I confirm that what arrives in the board looks like a CSS.

Patrick

**Comment by PatDeLux** [comment] 2016-02-09 08:17
Using Outlook 2010 on Windows. I don't know the version of Exchange server.

**Comment by PatDeLux** [comment] 2016-02-09 10:56
This morning I tested again after upgrading Kanboard to 1.0.25, and the mail from Outlook works quite fine now. (just losing bold formatting).
I am using plugin 1.0.2

**Comment by PatDeLux** [comment] 2016-03-07 15:33
Looks like the above issue has not been fixed in 1.0.3.
I had made the manual fix suggested by bdrayer in 1.0.2 on my instance, and after upgrading to 1.0.3 the issue is back.

**Closed** 2017-02-04 23:35 UTC
Labels: enhancement
